### ISSUE TITLE
Change endpoint to not include version

### ISSUE THREAD

**Issue by dblock** [dblock/open-weather-ruby-client#22]
As is, the README for stations API will not work because you need to use  the `api.openweathermap.org/data/3.0` endpoint. 

I propose to add `api_root` (e.g. `https://api.openweathermap.org`), `api_path`, e.g. `data`, and `api_version`, then combine these into `endpoint`. 

Then document that this now supports 2.5 and 3.0 endpoints.

**Comment by dblock** [comment]
I did this in https://github.com/dblock/open-weather-ruby-client/pull/23, so you don't need to specify `endpoint` to use the stations and measurements APIs.

**Comment by wasabigeek** [comment]
🙏
