### ISSUE TITLE
OpenSSL::SSL::SSLError on Heroku

### ISSUE THREAD

**Issue by sunny** [dblock/open-weather-ruby-client#26]
When using Heroku’s default stack, using this gem generates an SSL error. 

This is due to Ruby not being able to find the certification authority certificates (CA Certs) used to verify the authenticity of the request.

**Comment by sunny** [comment]
To fix it, you can add the following:

```rb
OpenWeather.configure do |config|
  config.ca_file = ENV["OPENWEATHER_API_CA_FILE"] if ENV["OPENWEATHER_API_CA_FILE"]
end
```

And configure the path to the CA certificate on Heroku:

```
heroku config:set OPENWEATHER_API_CA_FILE=/usr/lib/ssl/certs/ca-certificates.crt
```

**Comment by dblock** [comment]
I believe we need a fix like https://github.com/slack-ruby/slack-ruby-client/pull/416 here. Want to contribute it @sunny?

**Comment by sunny** [comment]
Thanks for the swift reviews and merges!
