### ISSUE TITLE
Missing 'summary' in OpenWeather::Models::OneCall::DailyWeather

### ISSUE THREAD

**Issue by mattlindsey** [dblock/open-weather-ruby-client#31]
Looks like some properties are missing, like `summary` of a forecast.  I might be able to help by adding them.

Also, I assume you don't want to support geocoding a name (city "New York City", for example) in order to return Forecast data?  The user of this gem should do that?

Also, Is there a reason you don't include state or country in your examples?  Aren't both supported?
```ruby
data = client.current_weather(city: 'London') # => OpenWeather::Models::City::Weather
data = client.current_weather(city: 'London, UK') # => OpenWeather::Models::City::Weather

**Comment by dblock** [comment]
Please do contribute missing fields! There's probably no good reason to include state or country, do add.

I think geocoding could be a great feature. If additional libraries/APIs are needed that aren't openweather I would consider depending on the dependencies the code brings.

**Comment by mattlindsey** [comment]
Closing this as I'm only interested in current weather now, not forecast.  

I'm going to do forecast later.  
I don't see `summary` in the models, so this issue might be valid.  Feel free to re-open it if you want.

And I do see option for state and country (optional) in your README, so I must have been confused since there are two different ways to get weather for a city:
```
data = client.current_weather(city: 'London')
client.current_city('New York', 'NY', 'US')
