### ISSUE TITLE
Support location names in other than ISO 3166

### ISSUE THREAD

**Issue by mattlindsey** [dblock/open-weather-ruby-client#35]
Not a huge deal, but `data = client.current_weather(city: city, units: units)` seems to blow up with `Faraday::ResourceNotFoundError` error when given given `Atlanta, GA`, `imperial`, but works fine with `Atlanta, Georgia`, `imperial`.   Data issue?

**Comment by dblock** [comment]
What’s the stack? Error from the server?

**Comment by mattlindsey** [comment]
Below the PR with the error message and context.  Could be I'm doing something wrong, and this is not urgent.  I'm not sure I'm not sure exactly how to see the server responsed.

I created a hacky fix around the exception, but would be nice to not need it.

https://github.com/andreibondarev/langchainrb/pull/193

**Comment by mattlindsey** [comment]
![image](https://github.com/dblock/open-weather-ruby-client/assets/5638339/0b742281-b5eb-409a-943e-5747e5af9947)

**Comment by dblock** [comment]
City is passed through as is [here](https://github.com/dblock/open-weather-ruby-client/blob/d82ac09ca1f419032c6247549f2ee4d2b6f40da3/lib/open_weather/endpoints/current.rb#L33) into the OpenWeather API documented in https://openweathermap.org/current#name. 

It says: _City name, state code and country code divided by comma, Please refer to [ISO 3166](https://www.iso.org/obp/ui/#search) for the state codes or country codes.
You can specify the parameter not only in English. In this case, the API response should be returned in the same language as the language of requested location name if the location is in our predefined list of more than 200,000 locations._

So the API uses https://www.iso.org/obp/ui/#iso:code:3166:US, which is `Georgia`.

You'll have to use something like https://github.com/carmen-ruby/carmen (maybe there exists a newer library?) to normalize/convert these. 

I'd welcome documentation on the fact that the city/state is ISO 3166, so will leave this issue open. Maybe you care to help?

**Comment by mattlindsey** [comment]
Thanks for explanation!  I can probably also tell the LLM in the Langchainrb gem to always return the full state name when 'function calling' my Weather tool.  And I will also submit PR soon here to update your doc concerning ISO 3066.

**Comment by dblock** [comment]
Adding examples is good. I would not add the "# Good" comment because they are all good and not say anything about the one that doesn't work. You could say "The OpenWeather API requires locations in the ISO 3166 format. Names that cannot be resolved will cause the API call to fail with `Faraday::ResourceNotFoundError `." or something like that.

**Comment by mattlindsey** [comment]
But in the case of state, ISO 3166 is not required, since NY and MA (for example) do (usually) work.
And I think we should keep the `Bad` line since it documents a case that common sense says should work.
